version: "3.9"

services:

  trino-coordinator:
    image: 'trinodb/trino:435'
    platform: linux/amd64
    hostname: trino-coordinator
    ports:
      - '8088:8080'
    volumes:
      - trino-catalog:/etc/catalog
    depends_on:
      - metastore

  postgres:
    image: postgres:13
    platform: linux/amd64
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore_db
    ports:
      - "5432:5432"

  metastore:
    image: apache/hive:3.1.3
    platform: linux/amd64
    container_name: metastore-standalone
    environment:
        - SERVICE_NAME=metastore
        - DB_DRIVER=postgres
        - SERVICE_OPTS=-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=hive
    ports:
      - "9083:9083"
    restart: always
    depends_on:
      - postgres

volumes:
  warehouse:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: ./warehouse
      o: bind

  trino-catalog:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: ./catalog
      o: bind

networks:
  default:
    name: lakehouse_net
    external: true